import { MCP_TOOL_NAMES } from './mcp-tool-catalog.js';
import {
  AGENT_READINESS_POLICY,
  CAPABILITY_INFERENCE_POLICY,
  RESOURCE_PREFERENCE_POLICY,
} from './scheduler.js';
import { workerReadinessDiagnostics, workerResourceDiagnostics } from './worker-diagnostics.js';

const VERSION = '0.1.0';

function summarizeWorker(worker) {
  return {
    id: worker.id,
    gatewayState: worker.gatewayState,
    adminState: worker.adminState,
    capabilities: worker.capabilities || [],
    labels: worker.labels || {},
    tools: Object.fromEntries(
      Object.entries(worker.inventory?.tools || {})
        .map(([name, tool]) => [name, {
          available: Boolean(tool.available),
          version: tool.version || null,
        }]),
    ),
    slots: {
      running: worker.runningSlots || 0,
      reserved: worker.reservedSlots || 0,
      available: worker.availableSlots ?? null,
      max: worker.maxConcurrency || 1,
    },
    agent: {
      preset: worker.agentPreset || null,
      configured: Boolean(worker.agentCommandConfigured),
      selfTest: worker.diagnostics?.agentSelfTest || null,
    },
    resources: workerResourceDiagnostics(worker),
    readiness: workerReadinessDiagnostics(worker),
  };
}

function summarizeSession(session) {
  return {
    id: session.id,
    status: session.status,
    title: session.title,
    workerId: session.assignedWorkerId || session.requestedWorkerId || null,
    currentTaskId: session.currentTaskId || null,
  };
}

export function buildGatewayCapabilities({ controlUrl, workers = [], sessions = [] }) {
  return {
    name: 'nado-agent',
    version: VERSION,
    controlUrl,
    generatedAt: new Date().toISOString(),
    auth: {
      type: 'bearer',
      adminHeader: 'Authorization: Bearer <NADO_TOKEN>',
      workerTokens: true,
    },
    surfaces: {
      http: true,
      cli: true,
      mcp: true,
      dashboard: `${controlUrl}/dashboard`,
      agentContext: `${controlUrl}/api/context`,
      mcpConfig: `${controlUrl}/api/mcp-config`,
    },
    mcp: {
      tools: MCP_TOOL_NAMES,
    },
    features: {
      workerDiscovery: true,
      workerInventory: true,
      workerInvites: true,
      workerBundles: true,
      workerSelfServiceEnrollment: true,
      workerPreflight: true,
      workerEvents: true,
      workerScopedTokens: true,
      signedWorkerRequests: true,
      signedWorkerRequestReplayProtection: true,
      workerEnrollmentTokenPruning: true,
      workerManagement: ['pause', 'resume', 'drain', 'shutdown', 'cancel_current', 'forget'],
      taskTypes: ['shell', 'agent'],
      routing: ['workerId', 'capabilities', 'autoCapabilityInference', 'labels', 'tools', 'priority', 'slots'],
      routingActionHints: true,
      autoGpuRouting: true,
      autoCapabilityRouting: ['gpu', 'docs', 'ppt'],
      workerResourceDiagnostics: true,
      workerReadinessDiagnostics: true,
      ipv6ControlUrls: true,
      networkActionHints: true,
      trustedProxyHeaders: true,
      dispatchPlanning: true,
      distributedTaskPlanning: true,
      requireRoutableSubmit: true,
      cliSubmitFlow: true,
      cliBatchSubmitFlow: true,
      mcpRunTaskFlow: true,
      mcpRunBatchFlow: true,
      sessions: true,
      batches: true,
      batchPlanning: true,
      batchDependencies: true,
      dependencyArtifacts: true,
      artifactPolicies: true,
      taskHistoryPruning: true,
      systemHistoryPruning: true,
      directArtifactDownload: true,
      groupedArtifactZipDownload: true,
      eventStreams: true,
      offlineRecovery: true,
      doctorSelfTest: true,
      doctorAgentSelfTest: true,
      readinessVerification: true,
      demoHealth: true,
      sandboxProfiles: ['default', 'isolated'],
    },
    networking: {
      workerConnectionModel: 'workers call the control HTTP API with outbound requests',
      ipv6LiteralUrls: true,
      ipv6LiteralFormat: 'http://[2001:db8::10]:8765',
      bindHostEnv: 'NADO_HOST',
      dockerHostBindEnv: 'NADO_DOCKER_HOST_IP',
      publicControlUrlEnv: 'NADO_PUBLIC_CONTROL_URL',
      trustProxyEnv: 'NADO_TRUST_PROXY',
      trustedProxyHeaders: ['X-Forwarded-Host', 'X-Forwarded-Proto'],
      diagnosticsEndpoint: 'GET /api/network',
      diagnosticsNextActionField: 'network.nextAction',
      diagnosticsActionCommandsField: 'network.nextAction.commands',
    },
    routingPolicy: {
      explicitWorkerWinsWhenEligible: true,
      sessionAffinity: true,
      constraints: ['workerId', 'requiredCapabilities', 'requiredLabels', 'requiredTools', 'slots'],
      automaticInference: CAPABILITY_INFERENCE_POLICY,
      agentReadiness: AGENT_READINESS_POLICY,
      resourcePreference: RESOURCE_PREFERENCE_POLICY,
      explainability: {
        taskField: 'task.scheduler',
        endpoint: 'GET /api/tasks/{taskId}/schedule',
        mcpTool: 'nado_explain_schedule',
      },
    },
    endpoints: {
      status: 'GET /api/status',
      capabilities: 'GET /api/capabilities',
      context: 'GET /api/context',
      mcpConfig: 'GET /api/mcp-config',
      network: 'GET /api/network',
      doctor: 'POST /api/doctor',
      verify: 'POST /api/verify',
      demoHealth: 'POST /api/demo/health',
      workers: {
        list: 'GET /api/workers',
        detail: 'GET /api/workers/{workerId}',
        preflight: 'GET /api/workers/{workerId}/preflight',
        events: 'GET|POST /api/workers/{workerId}/events',
        bundle: 'POST /api/workers/bundle',
        bootstrapBundle: 'POST /api/workers/bootstrap-bundle',
        enroll: 'POST /api/workers/enroll',
        register: 'POST /api/workers/register',
        heartbeat: 'POST /api/workers/{workerId}/heartbeat',
        claim: 'POST /api/workers/{workerId}/claim',
        manage: 'POST /api/workers/{workerId}/manage',
        forget: 'POST /api/workers/{workerId}/forget',
        tokens: 'GET|POST /api/worker-tokens',
        enrollmentTokens: 'GET|POST /api/worker-enrollment-tokens',
        enrollmentTokenPrunePreview: 'GET /api/worker-enrollment-tokens/prune',
        enrollmentTokenPrune: 'POST /api/worker-enrollment-tokens/prune',
      },
      tasks: {
        create: 'POST /api/tasks',
        list: 'GET /api/tasks',
        detail: 'GET /api/tasks/{taskId}',
        schedule: 'GET /api/tasks/{taskId}/schedule',
        events: 'GET /api/tasks/{taskId}/events',
        eventStream: 'GET /api/tasks/{taskId}/events/stream',
        manage: 'POST /api/tasks/{taskId}/manage',
        artifacts: 'GET /api/tasks/{taskId}/artifacts',
        artifactsJson: 'GET /api/tasks/{taskId}/artifacts/content',
        artifactJson: 'GET /api/tasks/{taskId}/artifacts/{artifactId}',
        artifactDownload: 'GET /api/tasks/{taskId}/artifacts/{artifactId}/download',
        artifactsZip: 'GET /api/tasks/{taskId}/artifacts/download',
        prunePreview: 'GET /api/tasks/prune?keep=20',
        prune: 'POST /api/tasks/prune',
        systemPrunePreview: 'GET /api/system-history/prune',
        systemPrune: 'POST /api/system-history/prune',
      },
      sessions: {
        create: 'POST /api/sessions',
        list: 'GET /api/sessions',
        pruneEmptyPreview: 'GET /api/sessions/prune-empty',
        pruneEmpty: 'POST /api/sessions/prune-empty',
        detail: 'GET /api/sessions/{sessionId}',
        close: 'POST /api/sessions/{sessionId}/close',
        artifacts: 'GET /api/sessions/{sessionId}/artifacts',
        artifactsJson: 'GET /api/sessions/{sessionId}/artifacts/content',
        artifactsZip: 'GET /api/sessions/{sessionId}/artifacts/download',
      },
      batches: {
        plan: 'POST /api/batches/plan',
        create: 'POST /api/batches',
        list: 'GET /api/batches',
        detail: 'GET /api/batches/{batchId}',
        report: 'GET /api/batches/{batchId}/report',
        events: 'GET /api/batches/{batchId}/events',
        eventStream: 'GET /api/batches/{batchId}/events/stream',
        manage: 'POST /api/batches/{batchId}/manage',
        artifacts: 'GET /api/batches/{batchId}/artifacts',
        artifactsJson: 'GET /api/batches/{batchId}/artifacts/content',
        artifactsZip: 'GET /api/batches/{batchId}/artifacts/download',
      },
      planner: {
        plan: 'POST /api/planner/plan',
        run: 'POST /api/planner/run',
      },
      dispatch: {
        plan: 'POST /api/dispatch/plan',
      },
      recovery: {
        offlineTasks: 'GET|POST /api/recovery/offline-tasks',
      },
    },
    cli: {
      examples: [
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js status --control ${controlUrl}`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js network --control ${controlUrl}`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js demo health --control ${controlUrl}`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js verify --control ${controlUrl}`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js dispatch plan --control ${controlUrl} --file ./batch.json`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js planner plan --control ${controlUrl} --prompt "large task" --mode map_reduce --json`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js planner run --control ${controlUrl} --prompt "large task" --mode map_reduce --require-routable --wait --report`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js worker logs --control ${controlUrl} --id <worker-id> --tail 50`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js worker bootstrap-bundle --control ${controlUrl} --out ./nado-worker-bootstrap.zip`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js worker bundle --control ${controlUrl} --id <worker-id> --issue-token --out ./nado-worker.zip`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js submit --control ${controlUrl} --capability code --command "echo hello"`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js submit --control ${controlUrl} --capability code --command "echo hello" --wait --download --out ./task-output`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js batch plan --title "work" --task "one: Do one thing" --out ./batch.json`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js batch submit --control ${controlUrl} --file ./batch.json --require-routable --wait --report --download --out ./batch-output`,
        `NADO_TOKEN="$NADO_TOKEN" node ./src/cli.js mcp --control ${controlUrl}`,
      ],
    },
    workers: workers.map(summarizeWorker),
    sessions: sessions.map(summarizeSession),
  };
}
